[Partition]
Type=esp
Format=vfat
CopyFiles=/efi:/
# FIXME: figure out if we could make repart guess the size
# This must not increase beyond 256MB as that would break DVD booting.
SizeMinBytes=240M
SizeMaxBytes=240M
