#
# Architecture specific settings
#

.x86_64:
  tags:
  - x86_64
  - gnome-build-meta
  variables:
    ARCH: x86_64

.i686:
  tags:
  - x86_64
  - gnome-build-meta
  variables:
    ARCH: i686

.aarch64:
  tags:
  - aarch64
  - gnome-build-meta
  variables:
    ARCH: aarch64

.arch-indep:
  tags:
  - gnome-build-meta
