variables:
  # Docker Images
  DOCKER_REGISTRY: "registry.gitlab.com/freedesktop-sdk/infrastructure/freedesktop-sdk-docker-images"
  DOCKER_IMAGE_ID: "307dbb43c80db04234f505f1ff4061772f948e5f"

  DOCKER_AMD64: "${DOCKER_REGISTRY}/bst16/amd64:${DOCKER_IMAGE_ID}"
  DOCKER_AARCH64: "${DOCKER_REGISTRY}/bst16/arm64:${DOCKER_IMAGE_ID}"

#
# Architecture specific settings
#

.x86_64:
  image: "${DOCKER_AMD64}"
  tags:
  - x86_64
  - gnome-build-meta
  variables:
    ARCH: x86_64

.i686:
  image: "${DOCKER_AMD64}"
  tags:
  - x86_64
  - gnome-build-meta
  variables:
    ARCH: i686

.aarch64:
  image: "${DOCKER_AARCH64}"
  tags:
  - aarch64
  - gnome-build-meta
  variables:
    ARCH: aarch64
