#
# Architecture specific settings
#

.x86_64:
  tags:
  - x86_64
  - gnome-build-meta
  variables:
    ARCH: x86_64
    ARCH_OPT: -o arch x86_64

.x86_64_v3:
  tags:
  - x86_64
  - gnome-build-meta
  variables:
    ARCH: x86_64
    X86_64_V3: "1"
    ARCH_OPT: -o arch x86_64 -o x86_64_v3 true

.aarch64:
  tags:
  - aarch64
  - gnome-build-meta
  variables:
    ARCH: aarch64
    ARCH_OPT: -o arch aarch64

.arch-indep:
  tags:
  - gnome-build-meta
