# The Incubator set is for apps that are being considered for core.
# Adding or removing elements from here should be approved by
# release team. Review the technical conditions to enter GNOME Incubator:
# https://gitlab.gnome.org/Teams/Releng/AppOrganization/-/blob/main/AppCriteria.md#incubation-criteria
#
# When updating this list, please also update the [incubating] section in
# files/gnome-mimeapps/quirks.toml
kind: stack
