kind: meson
sources:
- url: https://download.gnome.org/sources/gnome-todo/3.27/gnome-todo-3.27.90.tar.xz
  kind: tar
  ref: 1dc08b29ee6b2fc2842de152702f46d8cb8ff730a04aba3ac102749da7ef434a
depends:
- core-deps/appstream-glib.bst
- core-deps/evolution-data-server.bst
- core-deps/glib.bst
- core-deps/gnome-online-accounts.bst
- core-deps/gtk+-3.bst
- core-deps/libpeas.bst
- core-deps/meson.bst
- base.bst
