# The core set is not expected to change as frequently as core-deps or
# world. Adding or removing elements from here should be approved by
# release team. Current contacts: Michael Catanzaro or Javier Jardon.
#
# Additional design team approval is required before adding or removing
# desktop applications from core. Current contact: Allan Day.
kind: stack
depends:
- core/devhelp.bst
- core/dconf-editor.bst
- core/sysprof.bst
