# By default mutable /etc is in /var/lib/extensions.mutable/etc. We
# make a symlink to tell confext to actually use /etc as the writable
# layer.
d! /etc
d! /var/lib/extensions.mutable 0700
L! /var/lib/extensions.mutable/etc - - - - ../../../etc
